modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${keystone_id}"
version = "${keystone_version}"
displayName = "${keystone_name}"
authors = "${mod_authors}"
description = '''
${keystone_description}
'''

[[dependencies.${keystone_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${keystone_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
